[phases.install]
# Устанавливаем ВСЕ зависимости для сборки админ панели
cmds = [
  'npm ci'
]

[phases.build]
# Генерируем Prisma client и собираем приложение во время сборки
cmds = [
  'npx prisma generate',
  'npm run build',
  'echo "=== Checking build results ==="',
  'ls -la admin-panel/dist/ || echo "admin-panel/dist not found"',
  'ls -la public/ || echo "public dir not found"',
  'ls -la public/admin/ || echo "admin dir not found"'
]

[phases.prune]
# После сборки удаляем dev зависимости для уменьшения размера
cmds = [
  'echo "=== Before prune ==="',
  'ls -la public/admin/ || echo "admin dir not found before prune"',
  'npm prune --production',
  'echo "=== After prune ==="',
  'ls -la public/admin/ || echo "admin dir not found after prune"'
]

[start]
cmd = 'npm run start:railway' 