[phases.install]
# Устанавливаем ВСЕ зависимости для сборки админ панели
cmds = [
  'npm ci'
]

[phases.build]
# Генерируем Prisma client и собираем приложение во время сборки
cmds = [
  'npx prisma generate',
  'npm run build'
]

[phases.prune]
# После сборки удаляем dev зависимости для уменьшения размера
cmds = [
  'npm prune --production'
]

[start]
cmd = 'npm run start:railway' 