[phases.install]
# Устанавливаем зависимости для бэкенда
cmds = [
  'npm ci --only=production'
]

[phases.build]
# Генерируем Prisma client и собираем приложение во время сборки
cmds = [
  'npx prisma generate',
  'npm run build'
]

[start]
cmd = 'npm run start:railway' 