[build]
builder = "nixpacks"

[build.watch]
patterns = ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "**/*.json"]

[deploy]
numReplicas = 1
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
path = "/health"
port = 3000
timeoutSeconds = 10
intervalSeconds = 30 