[build]
builder = "nixpacks"

[build.watch]
patterns = ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "**/*.json"]

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
startCommand = "npm run deploy"

[deploy.healthcheck]
path = "/health"
port = 3000
timeoutSeconds = 10
intervalSeconds = 30